id: CEC38C4A4
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T20:40:12.268796'
last_modified: '2022-05-30T20:40:12.268801'
source_metadata:
  language:
    - bo
    - en
  alignments:
    AEC38C4A4:
      title: Short Vajrakīla Dokpa
    AB1B8DCF8:
      title: A Brief Daily Practice of the Wealth Deity White Jambhala
    AD789898E:
      title: A Prayer to Yumka Tsogyal
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
